from enum import Enum as PyEnum

class DebitNoteEmailStatusEnum(PyEnum):
    CREATED = "CREATED"
    PENDING_DATA_EXTRACTION = "PENDING_DATA_EXTRACTION"
    FAILED = "FAILED"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    PENDING_CW_UPLOAD = "PENDING_CW_UPLOAD"
    SKIPPED = "SKIPPED"
    DOWNLOADED = "DOWNLOADED"
